version: 2

sources:
  - name: olist
    description: This is a replica of the olsit database
    schema: olist_raw
    tables:
      - name: raw_customers
      - name: raw_geolocations
      - name: raw_order_items
      - name: raw_order_payments
      - name: raw_order_reviews
      - name: raw_orders
      - name: raw_product_category_name_translation
      - name: raw_products
      - name: raw_sellers